title: Datastructures and Algorithms Notes
email: jngai_@berkeley.edu
description: >- # this means to ignore newlines until "baseurl"
  A collection of my notes on Datastructures and Algorithms from Berkeley's CS61B classes
  plus notes and solutions to interesting leetcode problems I've tried. 

# Deployment settings
baseurl: "/datastructures"
url: "https://j-ngaiii.github.io/datastructures/" 

include:
  - sections

# automatically apply the layout to every file in /sections/
defaults:
  - scope:
      path: "sections"
    values:
      layout: "default"

# disable base math engine so the LaTeX in default.html doesn't bug
kramdown:
  math_engine: null

# Theme Selection
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag